library(readr)
library(dplyr)
# Match cells 15, 24, 26 and 28 of the supplied R notebook.
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) stop("Usage: Rscript scripts/prepare-canarsie.R /path/to/all_nyc_2026.csv")
df <- read_csv(args[1], col_select = c(TYPE, SALE_PRICE, GROSS_SQUARE_FEET, SALE_YEAR, NEIGHBORHOOD_NAME), show_col_types = FALSE)
df_clean <- df %>% filter(grepl('RESIDENTIAL', TYPE), SALE_PRICE > 0, GROSS_SQUARE_FEET > 0) %>% mutate(PRICE_PER_SQFT = SALE_PRICE / GROSS_SQUARE_FEET)
nbhd_agg <- df_clean %>% filter(SALE_YEAR >= 2009) %>% group_by(NEIGHBORHOOD_NAME) %>% summarise(median_price = median(SALE_PRICE, na.rm = TRUE), total_sales = n(), median_psf = median(PRICE_PER_SQFT, na.rm = TRUE), sd_price = sd(SALE_PRICE, na.rm = TRUE), .groups = 'drop') %>% filter(!is.na(median_psf), total_sales >= 2)
nbhd_scaled <- nbhd_agg %>% select(median_price, total_sales, median_psf, sd_price) %>% scale()
set.seed(42)
km1 <- kmeans(nbhd_scaled, centers = 3, nstart = 25)
nbhd_agg <- nbhd_agg %>% mutate(cluster = km1$cluster)
stopifnot(nrow(df) == 2083757, nrow(df_clean) == 643835, nrow(nbhd_agg) == 256)
my_row <- nbhd_agg %>% filter(NEIGHBORHOOD_NAME == 'CANARSIE')
stopifnot(my_row$total_sales == 5955, my_row$median_price == 503500, abs(my_row$median_psf - 268.4049) < .0001, my_row$cluster == 2)
stopifnot(identical(as.integer(table(nbhd_agg$cluster)), c(167L, 50L, 39L)))
dir.create('data', showWarnings = FALSE)
write_csv(nbhd_agg, 'data/canarsie-neighborhoods.csv')
print(my_row)
print(nbhd_agg %>% group_by(cluster) %>% summarise(n=n(), avg_median_psf=mean(median_psf)))
cat('Dataset years:', min(df$SALE_YEAR), max(df$SALE_YEAR), '\n')
